### ISSUE TITLE
DMX Input?

### ISSUE THREAD

**Issue by Nick-116** [andyboeh/esphome-dmx512#14]
Hello,
I want to trigger things in ESPhome based on a DMX input. Is this possible to implement? It looks like the integration only supports outputting DMX, not inputs.

**Comment by andyboeh** [comment]
Excactly, it's output only. For supporting input, the biggest challenge is detecting the break signal. I have neither the hardware to test this nor the need to implement it so: PRs are welcome.
Until then, I'm closing this.
