### ISSUE TITLE
Receive DMX support

### ISSUE THREAD

**Issue by kc5uvc** [andyboeh/esphome-dmx512#21]
Is there any support offered to receive a DMX signal, process, and react accordingly?  I would like to be able to control a series of relays based upon DMX  information received.  Ideally I would like to keep this in the ESPHome platform on an ESP32 device.

**Comment by andyboeh** [comment]
No, that's neither possible with the current implementation nor planned. Unfortunately, DMX doesn't play nice with the UART implementation in ESPHome and I doubt that this can be easily implemented.

Feel free to add support for it and create a PR!
