### ISSUE TITLE
Would this work with this device?

### ISSUE THREAD

**Issue by dgrnbrg** [andyboeh/esphome-dmx512#24]
I am wondering if I could use this library with the https://www.olimex.com/Products/Modules/Interface/MOD-RS485/open-source-hardware . It would be a nice combination, since then it'd be an entirely off the shelf Ethernet<->DMX with esphome solution.

Specifically, I'd appreciate if you could tell me how the disconnection of the pins generates the break signal, and if it's relying on specific behavior of the rs485 chips you suggest.

Thanks!

**Comment by andyboeh** [comment]
I don't know, just try it and report back by creating a PR and improving the documentation.
