### ISSUE TITLE
Reading DMX controllers

### ISSUE THREAD

**Issue by tensiondriven** [andyboeh/esphome-dmx512#28]
Hi Andy - Thanks for making this library for ESPHome!

I'm fantasizing about using a DMX controller to send control signals to ESPHome.  So basically, to be able to create sensors for Home Assistant using ESPHome,attached to an inexpensive DMX controller.

Any chance that it would be trivial to build such a library?  I know that isn't the intention of *this* library, but thought this might be an appropriate place to ask.

**Comment by andyboeh** [comment]
See #14, #21 and #26.

**Comment by tensiondriven** [comment]
Thank you
