### ISSUE TITLE
Lambda for dimmer

### ISSUE THREAD

**Issue by stijnb1234** [andyboeh/esphome-dmx512#31]
I have a DMX dimmer in my circuit with weird values:
Below 124 is off
124 - 150 is dimming from 0-100%
Above 150 is on

How can I do this with this component? Can I use the lambda, and how?

**Comment by andyboeh** [comment]
Sure: Create a template output and add your logic to the `write_value` function:

https://esphome.io/components/output/template.html

**Comment by stijnb1234** [comment]
So far I understand. But what are the input values (which range?) and what are the output values?

**Comment by andyboeh** [comment]
The values at the output are in the range 0.0 to 1.0, it's a float output. The DMX component calculates the 0-254 values based on this float range. So you are dealing with two float ranges between 0 and 1 here and you need to map your values here.
