### ISSUE TITLE
Feature request: general mute switch

### ISSUE THREAD

**Issue by nagyrobi** [andyboeh/esphome-dmx512#7]
From practical perspective: would be nice to have a switch implemented in this component which would drastically cut the output of the ESP when turned on: the equivalent of DMX cable pulled out.

By muting the output I mean simply not to send any signal at all, keep the GPIO in low state. DMX fixtures will all turn off when they don't get any signal on their inputs, and turn back on when signal comes back.

Use case 1: for longer periods turned off, minimize energy consumption and RF interference noise (reduce electrosmog)
Use case 2: re-arrange lights settings in blind (without being seen).

**Comment by andyboeh** [comment]
I do understand your request and use-case. I'm not yet sure how to best implement it, one way could be an additional switch the is attached to a universe that mutes the signal if it's on.
I can try to come up with something when I have some free time.

**Comment by nagyrobi** [comment]
I thought at about the way you hooked to the output pin to generate the break signal. Perhaps this switch could override the timing of that - keep it in break state as long as the switch is ON.

**Comment by andyboeh** [comment]
I just noticed that this is already implemented: Do **not** define the enable_pin but rather define it is a switch in ESPHome. The switch enables/disabled the RS485 driver/receiver, hence you get the desired effect.

**Comment by nagyrobi** [comment]
Hmmmm...

**Comment by andyboeh** [comment]
> There are many outthere which don't have such a control option as they do it automatically based on the data input.

Could you point me to one?

**Comment by nagyrobi** [comment]
> Could you point me to one?

The ones marked with _automatic flow control_. What they do is monitor the data input pin, and enable transmission to the bus as soon as data comes in and keep it enabled for a short while after data has finished. You can't control that manually.
Some do it very simply with a capacitor...

Eg:
https://www.aliexpress.com/item/32705625990.html
https://www.aliexpress.com/item/1005001580305871.html

**Comment by nagyrobi** [comment]
> Do **not** define the enable_pin but rather define it is a switch in ESPHome. The switch enables/disabled the RS485 driver/receiver, hence you get the desired effect.

Your idea works well with MAX485-M.

For an ESP8266 the connection looks like this:

```
MAX485-M RE & DE -> GPIO13 (in Wemos D1 Mini it's marked D7)
MAX485-M VCC     ->  +3.3V
MAX485-M GND     -> GND
MAX485-M DI      -> GPIO2 (on Wemos D1 Mini it's marked D4)
MAX485-M A       -> XLR 3
MAX485-M B       -> XLR 2
MAX485-M GND     -> XLR 1
```

Configuration:

```
switch:
- platform: gpio
  name: 'DMX output MUTE'
  pin:
    number: GPIO13
    inverted: true
```

**Comment by andyboeh** [comment]
Yeah, these cheap modules probably just have the pins 2 and 3 hardwired to VCC.
